export const BoardActionTypes = {
  TOGGLE_NEW_BOARD: 'TOGGLE_NEW_BOARD',
  ADD_BOARD_START: 'ADD_BOARD_START',
  ADD_BOARD_SUCCESS: 'ADD_BOARD_SUCCESS',
  ADD_BOARD_FAILURE: 'ADD_BOARD_FAILURE',
  LOAD_USER_BOARDS_START: 'LOAD_USER_BOARDS_START',
  LOAD_USER_BOARDS_SUCCESS: 'LOAD_USER_BOARDS_SUCCESS',
  LOAD_USER_BOARDS_FAILURE: 'LOAD_USER_BOARDS_FAILURE',
};
